/**
 * Paper design skills registered into ctx.skills.
 *
 * code-to-design and design-to-code mirror the Cursor Paper plugin skill
 * bodies verbatim. paper-design is the progressive-disclosure tool-reference
 * index (adapted from pi-paper-design, which already indexes the live
 * paper-mcp-instructions guide). The ensure-paper-started Cursor rule is
 * folded into the standing rules and tool descriptions — DSH has no rules
 * file, so startup guidance lives in the prompt section and descriptions.
 *
 * @module dsh-paper-design/src/skills
 */

import type { Context } from '@deepseek-ai/cordis'
const CODE_TO_DESIGN = [
  "---",
  "name: code-to-design",
  "description: Generate a Paper design from the project's codebase — using its tokens, styles, and components as context.",
  "---",
  "",
  "Before starting, ensure Paper Desktop is running with a file open. If a connection to the Paper MCP server fails, remind the user to open Paper Desktop first.",
  "",
  "Read the project's stylesheets, design tokens, or theme files to understand the existing design language. Then create a new artboard in Paper and build the requested UI using the codebase's actual colors, typography, spacing, and component patterns — not generic defaults.",
].join('\n')

const DESIGN_TO_CODE = [
  "---",
  "name: design-to-code",
  "description: Turn a Paper design into production code using the project's existing conventions.",
  "---",
  "",
  "Before starting, ensure Paper Desktop is running with a file open. If a connection to the Paper MCP server fails, remind the user to open Paper Desktop first.",
  "",
  "Read the selected frame or artboard from Paper — including structure, styles, text content, and computed layout. Then generate production-ready components in the project's framework and coding style. Match the design's layout, spacing, typography, and colors using the codebase's existing conventions (e.g. Tailwind classes, CSS modules, design tokens, styled-components).",
].join('\n')

const PAPER_DESIGN = [
  "---",
  "name: paper-design",
  "description: Use when designing in Paper via paper_* tools. Progressive disclosure: this skill indexes every paper-mcp-instructions topic (review, mood/palette, quality, workflows, typography, etc.) — load full body via early-turn injection or paper_get_guide. Also indexes tools and HTML rules.",
  "---",
  "",
  "# Paper Design (MCP)",
  "",
  "Use this skill for **tool reference** when working with Paper via the DSH bridge. All tools are prefixed `paper_`. Paper Desktop must be running with a file open.",
  "",
  "## Guidance sources (do not duplicate)",
  "",
  "| Source | Role |",
  "|--------|------|",
  "| **System prompt injection** | Standing rules every turn when connected; full `paper-mcp-instructions` guide for the first few turns after connect/`/paper-reconnect` |",
  "| **`paper_get_guide`** | **Use as needed** for full design/workflow instructions (`paper-mcp-instructions`), mobile status bar (`mobile-status-bar`), or Figma import (`figma-import`). Call it after early turns, if context was compressed, before a major new design if unsure, or anytime standing rules alone are not enough. |",
  "| **This skill** | Tool tables, HTML conventions, and a **complete index** of every `paper-mcp-instructions` section (progressive disclosure → load full body via injection or `paper_get_guide`) |",
  "",
  "---",
  "",
  "## Progressive disclosure — full `paper-mcp-instructions` index",
  "",
  "**How to use:** This skill **indexes** every section of the live guide. It does **not** replace the guide body. When a row applies to your task, ensure you have the full text — from early-turn system-prompt injection, or by calling:",
  "",
  "`paper_get_guide({ topic: \"paper-mcp-instructions\" })`",
  "",
  "Then follow that body with `paper_*` tools. Do not invent rules from memory when the guide covers the topic.",
  "",
  "| # | Guide section | Indexed contents (load guide for full text) | Typical tools / actions |",
  "|---|---------------|-----------------------------------------------|-------------------------|",
  "| 1 | **Review Checkpoints — MANDATORY** | After each new section: screenshot; one-line verdict; fix before continuing. Checklist: **Spacing**, **Typography**, **Contrast**, **Alignment**, **Artboard fit** (`height: \"fit-content\"`, never guess fixed heights), **Repetition**. Targeted fixes only — do not delete/restart whole frames for overflow. | `paper_get_screenshot`, `paper_update_styles` |",
  "| 2 | **Design Quality — IMPORTANT** | Craft bar for Paper: minimalism (prefer removal), warm human touch, deliberate spacing rhythm, asymmetry + scale contrast, authoritative hierarchy (not component-library sameness), impressiveness vs clarity by goal, **playful register** (duos/trios accents, stickers/tilts, offset shadows, hand-drawn marks, mascots, quippy copy — pick 1–2), multiple directions must be tangibly different, surfaces over cards, avoid late-2010s gradient/shadow excess (tasteful if requested), Swiss editorial type (display vs label weight contrast, tracking), **default light mode**. | `paper_write_html`, `paper_update_styles`, `paper_get_font_family_info` |",
  "| 3 | **Mood word & scene-derived color** | Commit to a **mood word** before hex (physical condition/register). Derive every color from a named object in that scene. One intense color moment > five. Mood candidates mix obvious + less-obvious; pick **not** first instinct. Full mood vocabulary and examples live in the guide. | Brief in chat; then tokens / styles |",
  "| 4 | **Proven background × accent pairings** | Named families to interpret (not fixed hex): mineral, maritime, rusted, industrial, bookish, chapel, candlelit, botanical, tropical, alpine, nocturnal, phosphor/terminal, vehicle dashboard, signage, gallery/pop, editorial/saturated, hypertext, highlighter, brutalist. Creative substitution OK within principles. | Guide body for the full pairing list |",
  "| 5 | **Pairings to avoid** | Clichés: warm off-white × terracotta/red/orange; warm off-white × fluorescent; navy/charcoal × electric purple/lime/teal; pure white × muted earth; tinted warm ground × high-chroma accent. | Guide body for exact avoid-list |",
  "| 6 | **Neutrals** | Pure white `#FFFFFF` as everyday ground; off-white only for specific moods; grays from scene or true neutrals; pure black when high-chroma / inky-nocturnal / requested; else tint darks toward mood. | Guide body for neutral rules |",
  "| 7 | **Secondary accents** | OK for categories, data viz, semantic states; same scene as primary; one primary anchor; keep saturation conservative; reduce other flourishes when using many colors. | Guide body |",
  "| 8 | **Text contrast & tiny type** | Contrast non-negotiable; muted/opacity sparingly; glance-readable; extra care <16px; avoid ≤12px except dense productivity or stylistic all-caps. | Guide body |",
  "| 9 | **Vague / capability-test prompts** | No existing visual context → impressive simple deliverable that wows quickly. | Guide body |",
  "| 10 | **Placeholder content** | Realistic text/images. Design-app mentions → **Paper only**. MUST NOT mention Figma or Sketch in placeholders. | `paper_set_text_content`, `paper_write_html` |",
  "| 11 | **Vertical lane alignment** | Repeated rows: fixed-width slots + `flexShrink: 0` for icons/indicators/actions (even when empty). Never gap-alone alignment. After 3+ rows, screenshot and verify lanes. | `paper_write_html`, `paper_get_screenshot` |",
  "| 12 | **Before Creating New Designs** | Unless user gave a full design system: post **design brief as chat** before any mutations. Format: Mood candidates → Mood chosen (+ why not first instinct) → Palette (5–6 hex + roles) → Type → Direction. No `create_artboard` / `write_html` until brief posted. | Chat message; then `paper_create_artboard` |",
  "| 13 | **Workflow Tips — realtime canvas** | Write small, write often (~one visual group; break >~15 lines HTML). Never batch whole components. Screenshot after meaningful edits. Visible progress every few seconds. `<x-paper-clone node-id=\"…\" />`. `fileId` sticky vs explicit multi-file. | `paper_write_html`, `paper_duplicate_nodes` |",
  "| 14 | **Context & exploration steps** | (1) `get_basic_info` — mobile/tablet/desktop widths. (2) **Design tokens**: ALWAYS use existing file tokens via `var(--…)`. (2.1) Generating new design tokens: Tailwind v4 namespaces exactly — `--font-*`, `--color-*`, `--breakpoint-*`, `--container-*`, `--text-*`, `--font-weight-*`, `--tracking-*` (em), `--leading-*` (px), `--radius-*`. (3) `get_selection`. (4) `get_tree_summary` / children / node_info. (5) `get_screenshot` (1x default; 2x for fine text). (6) `get_jsx`. (7) `get_computed_styles` batch. (8) Mandatory screenshot critiques via Review Checkpoints. No raw node IDs in user-facing text. | Matching `paper_*` tools |",
  "| 15 | **Writing new designs** | Brief → `create_artboard` → incremental content → SVG tokens on stroke/fill → prefer `duplicate_nodes` + styles/text when cheaper → MUST `finish_working_on_nodes`. | `paper_create_artboard`, `paper_write_html`, … |",
  "| 16 | **Editing existing designs** | Incremental updates; `move_nodes` to reparent/reorder (preserve IDs); MUST `finish_working_on_nodes`. | `paper_move_nodes`, … |",
  "| 17 | **Design → codebase** | Exact values from `get_jsx`, `get_computed_styles`, `get_fill_image`. Never build code from screenshots (screenshots = QA only). Match user's codebase conventions. | Read tools + repo conventions |",
  "| 18 | **Working with text — fonts** | Prefer fonts already in `get_basic_info`. MUST `get_font_family_info` before first typographic styling (local, Google Fonts, web-safe, system-ui). | `paper_get_font_family_info` |",
  "| 19 | **Typographic units** | MUST `px` font-size; SHOULD `em` letter-spacing; SHOULD `px` line-height (relative OK if no subpixels). | Styles / write_html |",
  "| 20 | **Importing from Figma** | Not in main guide body — call `paper_get_guide({ topic: \"figma-import\" })` for the full workflow. | `paper_get_guide` |",
  "| 21 | **Mobile status bar** | Not in main guide body — call `paper_get_guide({ topic: \"mobile-status-bar\" })` for paste-ready markup; do not hand-draw. | `paper_get_guide`, `paper_write_html` |",
  "",
  "**Specialized guide topics** (separate from `paper-mcp-instructions`): `mobile-status-bar`, `figma-import`.",
  "",
  "---",
  "",
  "## Standing rules (summary)",
  "",
  "Injected in full by the bridge when connected. Essentials:",
  "",
  "- `paper_get_basic_info` first; `paper_get_selection` for focus",
  "- MUST `paper_get_font_family_info` before first typographic styling; `px` for font sizes, `em` for letter-spacing, `px` for line-height",
  "- Design brief before new mutations; one visual group per `paper_write_html`",
  "- Prefer `paper_duplicate_nodes` + `paper_update_styles` + `paper_set_text_content` when cheaper",
  "- Screenshot + review after meaningful changes; clip → `height: \"fit-content\"`",
  "- Fixed-width slots (`flexShrink: 0`) for repeated row columns",
  "- MUST `paper_finish_working_on_nodes` when done; no raw node IDs in user text",
  "- Code export via `paper_get_jsx` / computed styles / fill image — not screenshots alone",
  "",
  "For any indexed row above (review checklist, mood pairings, playful register, token namespaces, etc.) → early-turn injection or **`paper_get_guide({ topic: \"paper-mcp-instructions\" })`**.",
  "",
  "---",
  "",
  "## Quick start",
  "",
  "1. `paper_list_files` — verify MCP + list files  ",
  "2. `paper_open_file` — by `fileId` or URL (sticky)  ",
  "3. `paper_get_basic_info` — artboards, fonts, tokens  ",
  "4. `paper_get_selection` — user focus  ",
  "",
  "Default artboard sizes: **Desktop** 1440×900, **Tablet** 768×1024, **Mobile** 390×844 — for mobile status bar markup call `paper_get_guide({ topic: \"mobile-status-bar\" })` (do not hand-draw).",
  "",
  "---",
  "",
  "## Tool reference",
  "",
  "Pass optional `fileId` when working across multiple files; otherwise the sticky file applies.",
  "",
  "### Files & navigation",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_list_files` | — | Params: `limit`. Most recent first. |",
  "| `paper_open_file` | `fileId` | Optional `pageId`. Sticky file. |",
  "| `paper_create_file` | — | Optional `name`, `cloneFileId`. Then open. |",
  "| `paper_create_page` | — | Optional `name`, `fileId`. Open to switch. |",
  "",
  "### Reading",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_get_basic_info` | — | Call first. Artboards, fonts, tokens. |",
  "| `paper_get_selection` | — | Selected nodes. |",
  "| `paper_get_node_info` | `nodeId` | Details + text for Text nodes. |",
  "| `paper_get_children` | `nodeId` | Direct children. |",
  "| `paper_get_tree_summary` | `nodeId` | Compact subtree; optional `depth`. |",
  "| `paper_get_screenshot` | `nodeId` | **Image** result. `scale` 1 or 2; `transparent`. |",
  "| `paper_get_jsx` | `nodeId` | Tailwind (default) or inline-styles. |",
  "| `paper_get_computed_styles` | `nodeIds` | Batch CSS. |",
  "| `paper_get_fill_image` | `nodeId` | Image fill JPEG. |",
  "| `paper_find_nodes` | — | `filters` and/or `textValue`. |",
  "| `paper_get_font_family_info` | `familyNames` | MUST before first type styling. |",
  "| `paper_get_guide` | `topic` | `paper-mcp-instructions`, `mobile-status-bar`, `figma-import`. **Use as needed.** |",
  "",
  "### Comments / review",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_list_comment_threads` | — | Open threads by default; many filters. |",
  "| `paper_get_comment_thread` | `commentThreadId` | Full thread. |",
  "| `paper_list_comment_thread_authors` | — | Authors for filters. |",
  "| `paper_set_comment_thread_status` | `commentThreadId`, `status` | `resolved` \\| `open`. |",
  "",
  "### Writing / editing",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_write_html` | `html`, `targetNodeId`, `mode` | `insert-children` \\| `replace`. One visual group per call. |",
  "| `paper_create_artboard` | `name`, `styles` | `width` + `height` required (e.g. `\"1440px\"`). |",
  "| `paper_set_text_content` | `updates` | Text nodes only. |",
  "| `paper_rename_nodes` | `updates` | Layer names. |",
  "| `paper_duplicate_nodes` | `nodes` | Deep clone + ID map. |",
  "| `paper_move_nodes` | `moves` | Reparent/reorder; prefer over rewrite. |",
  "| `paper_update_styles` | `updates` | Batch CSS / tokens. |",
  "| `paper_delete_nodes` | `nodeIds` | Includes descendants. |",
  "| `paper_finish_working_on_nodes` | — | **MANDATORY** when done. |",
  "",
  "### Tokens",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_get_tokens` | — | Optional `types`, `namePattern`, `format`. |",
  "| `paper_create_tokens` | `tokens` | Semantic colors first; sizes smallest-first. |",
  "| `paper_set_tokens` | `tokens` | Rename / update / delete. |",
  "",
  "### Export",
  "",
  "| Tool | Required | Notes |",
  "|------|----------|-------|",
  "| `paper_export` | `nodes` | Don't override defaults unless asked. |",
  "| `paper_export_combined_pdf` | `nodeIds` | One PDF by canvas order. |",
  "",
  "---",
  "",
  "## HTML rules for `paper_write_html`",
  "",
  "- **Incremental** — one visual item per call. Card with header + 4 rows + footer = 6+ calls.",
  "- Clone: `<x-paper-clone node-id=\"A-01\" style=\"...\" />`",
  "- Inline styles only; tokens as `var(--color-primary)`",
  "- Flex + padding + gap (not margin). No `display: grid`, inline, or HTML tables.",
  "- Absolute OK for decoration; don't cover the whole artboard.",
  "- `layer-name` attribute; local images `paper-asset:///absolute/path`",
  "- No emoji icons — SVG or images",
  "",
  "---",
  "",
  "## Typical flows",
  "",
  "**New design:** brief → `paper_create_artboard` → incremental write → screenshot/review → `paper_finish_working_on_nodes`. Load full instructions via injected guide or `paper_get_guide`.",
  "",
  "**Edit:** `paper_get_basic_info` → selection → tree/screenshot → targeted edits / `paper_move_nodes` → finish.",
  "",
  "**Design → code:** `paper_get_jsx` / computed styles / fill image — never sizes/colors from screenshots alone.",
  "",
  "**Connection:** Paper Desktop with a file open. `/paper-reconnect` refreshes MCP session, guide cache, and early-turn guide injection budget.",
].join('\n')


/** Register the three paper design skills. Returns disposers. */
export function applySkills(ctx: Context): () => void {
  const disposers = [
    ctx.skills.register({
      name: 'code-to-design',
      description: "Generate a Paper design from the project's codebase — using its tokens, styles, and components as context.",
      source: 'bundled',
      content: CODE_TO_DESIGN,
    }),
    ctx.skills.register({
      name: 'design-to-code',
      description: "Turn a Paper design into production code using the project's existing conventions.",
      source: 'bundled',
      content: DESIGN_TO_CODE,
    }),
    ctx.skills.register({
      name: 'paper-design',
      description: "Tool reference and progressive-disclosure index for the Paper MCP bridge (paper_* tools).",
      source: 'bundled',
      content: PAPER_DESIGN,
    }),
  ]
  return () => { for (const dispose of disposers) dispose() }
}
